#!/bin/bash
#

function get_latest {
    FILENUM=$(gphoto2 -L | grep -i "^#" | tail -n 1 | awk '{print $1}')
    if [ -z "${FILENUM}" ]; then
      echo -1
    else
      echo ${FILENUM:1}
    fi
}

function download {
    echo "download $1"
    gphoto2 --get-file=$1
    curl -T *.JPG ftp://134.169.35.4:2121/ --user user:12345
    rm *.JPG
}

LAST=-1

while [ 1 == 1 ]; do
    LATEST=$(get_latest)

    if [ ${LATEST} -eq -1 ]; then
        sleep 1
        continue
    fi

    if [ ${LAST} -ne ${LATEST} ]; then
        download ${LATEST}
        LAST=${LATEST}
    fi
done
