<html>
<head>
	<title>PiCamIf Config Interface</title>
</head>
<body>
<h1>PiCamIf Config Interface</h1>

<?php
if( $_REQUEST["action"] == "Save" ) {
	$Config = Array(
		"ftpServer" 	=> $_REQUEST["ftpServer"],
		"ftpPort"	=> $_REQUEST["ftpPort"],
		"ftpUser"	=> $_REQUEST["ftpUser"],
		"ftpPassword"	=> $_REQUEST["ftpPassword"],
		"ftpEnabled"	=> $_REQUEST["ftpEnabled"],
		);

	if( is_writable("/etc/ftpUpload.conf") ) {
		$fp = fopen("/etc/ftpUpload.conf", "w");
		fputs($fp, json_encode($Config));
		fclose($fp);

		echo "Saved config to " . "/etc/ftpUpload.conf" . "<br />\n";
	} else {
		echo "Unable to write to " . "/etc/ftpUpload.conf" . "<br />\n";
	}

	if( is_writable("/etc/ftpUpload.cmd") ) {
		$fp = fopen("/etc/ftpUpload.cmd", "w");
		fputs($fp, "# DO NOT EDIT THIS FILE\n");
		fputs($fp, "ftpServer=\"" . $_REQUEST["ftpServer"] . "\"\n");
		fputs($fp, "ftpPort=\"" . $_REQUEST["ftpPort"] . "\"\n");
		fputs($fp, "ftpUser=\"" . $_REQUEST["ftpUser"] . "\"\n");
		fputs($fp, "ftpPassword=\"" . $_REQUEST["ftpPassword"] . "\"\n");
		fputs($fp, "ftpEnabled=\"" . $_REQUEST["ftpEnabled"] . "\"\n");
		fclose($fp);

		echo "Saved config to " . "/etc/ftpUpload.cmd" . "<br />\n";
	} else {
		echo "Unable to write to " . "/etc/ftpUpload.cmd" . "<br />\n";
	}
} 

if( $_REQUEST["action"] == "Test" ) {
	echo "<hr>\n";
	echo "<h2>Testing...</h2>\n";
	flush();

	$conn_id = ftp_connect($_REQUEST["ftpServer"], $_REQUEST["ftpPort"]);
	
	if( !$conn_id ) {
		echo "Unable to connect to " . $_REQUEST["ftpServer"] . ":" . $_REQUEST["ftpPort"] . "<br />\n";
	} else {
		echo "Connection to " . $_REQUEST["ftpServer"] . ":" . $_REQUEST["ftpPort"] . " ok<br />\n";
	}
	flush();

	$login_result = ftp_login($conn_id, $_REQUEST["ftpUser"], $_REQUEST["ftpPassword"]);

	if( !$login_result ) {
		echo "Unable to login with " . $_REQUEST["ftpUser"] . " and " . $_REQUEST["ftpPassword"] . "<br />\n";
	} else {
		echo "Login with " . $_REQUEST["ftpUser"] . " and " . $_REQUEST["ftpPassword"] . " ok<br />\n";
	}
	flush();

	echo "<hr>\n";

	$ftpServer = $_REQUEST["ftpServer"];
	$ftpPort = $_REQUEST["ftpPort"];
	$ftpUser = $_REQUEST["ftpUser"];
	$ftpPassword = $_REQUEST["ftpPassword"];
	$ftpEnabled = $_REQUEST["ftpEnabled"];
}

elseif( is_file("/etc/ftpUpload.conf") && is_readable("/etc/ftpUpload.conf") && is_writable("/etc/ftpUpload.conf") ) {
	$data = json_decode(file_get_contents("/etc/ftpUpload.conf"));
	
	$ftpServer = $data->ftpServer;
	$ftpPort = $data->ftpPort;
	$ftpUser = $data->ftpUser;
	$ftpPassword = $data->ftpPassword;
	$ftpEnabled = $data->ftpEnabled;
}

elseif( !is_file("/etc/ftpUpload.conf") || !is_readable("/etc/ftpUpload.conf") || !is_writable("/etc/ftpUpload.conf") ) {
	$ftpServer = $_SERVER["REMOTE_ADDR"];
	$ftpPort = 2121;
	$ftpUser = "user";
	$ftpPassword = "12345";
	$ftpEnabled = "on";
}

?>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<table border=0>
<tr>
	<td>FTP Server:</td>
	<td><input name="ftpServer" value="<?php echo $ftpServer; ?>" /></td>
</tr>
<tr>
	<td>FTP Port:</td>
	<td><input name="ftpPort" value="<?php echo $ftpPort; ?>" /></td>
</tr>
<tr>
	<td>FTP User:</td>
	<td><input name="ftpUser" value="<?php echo $ftpUser; ?>" /></td>
</tr>
<tr>
	<td>FTP Password:</td>
	<td><input name="ftpPassword" value="<?php echo $ftpPassword; ?>" /></td>
</tr>
<tr>
	<td colspan="2"><input type="checkbox" name="ftpEnabled" <?php echo $ftpEnabled ? "checked" : ""; ?> /> FTP Upload Enabled</td>
</tr>
<tr>
	<td colspan="2"><input name="action" type="submit" value="Save" /> <input name="action" type="submit" value="Test" /></td>
</tr>
</table>
</form>

<hr>
<h2>Filesystem Overview</h2>
<pre>
<?php
passthru("df -h | grep /data/pictures");
passthru("df -h | grep /$ | head -n 1");
?>
</pre>

</body>
</html>
